

create table `countries` (
	`id` int (10),
	`sortname` varchar (573),
	`name` varchar (573),
	`created_at` timestamp ,
	`updated_at` timestamp 
); 
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('1','AF','Afghanistan',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('2','AL','Albania',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('3','DZ','Algeria',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('4','AS','American Samoa',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('5','AD','Andorra',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('6','AO','Angola',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('7','AI','Anguilla',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('8','AQ','Antarctica',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('9','AG','Antigua And Barbuda',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('10','AR','Argentina',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('11','AM','Armenia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('12','AW','Aruba',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('13','AU','Australia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('14','AT','Austria',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('15','AZ','Azerbaijan',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('16','BS','Bahamas The',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('17','BH','Bahrain',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('18','BD','Bangladesh',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('19','BB','Barbados',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('20','BY','Belarus',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('21','BE','Belgium',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('22','BZ','Belize',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('23','BJ','Benin',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('24','BM','Bermuda',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('25','BT','Bhutan',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('26','BO','Bolivia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('27','BA','Bosnia and Herzegovina',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('28','BW','Botswana',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('29','BV','Bouvet Island',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('30','BR','Brazil',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('31','IO','British Indian Ocean Territory',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('32','BN','Brunei',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('33','BG','Bulgaria',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('34','BF','Burkina Faso',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('35','BI','Burundi',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('36','KH','Cambodia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('37','CM','Cameroon',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('38','CA','Canada',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('39','CV','Cape Verde',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('40','KY','Cayman Islands',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('41','CF','Central African Republic',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('42','TD','Chad',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('43','CL','Chile',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('44','CN','China',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('45','CX','Christmas Island',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('46','CC','Cocos (Keeling) Islands',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('47','CO','Colombia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('48','KM','Comoros',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('49','CG','Congo',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('50','CD','Congo The Democratic Republic Of The',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('51','CK','Cook Islands',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('52','CR','Costa Rica',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('53','CI','Cote D\'Ivoire (Ivory Coast)',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('54','HR','Croatia (Hrvatska)',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('55','CU','Cuba',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('56','CY','Cyprus',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('57','CZ','Czech Republic',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('58','DK','Denmark',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('59','DJ','Djibouti',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('60','DM','Dominica',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('61','DO','Dominican Republic',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('62','TP','East Timor',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('63','EC','Ecuador',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('64','EG','Egypt',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('65','SV','El Salvador',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('66','GQ','Equatorial Guinea',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('67','ER','Eritrea',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('68','EE','Estonia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('69','ET','Ethiopia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('70','XA','External Territories of Australia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('71','FK','Falkland Islands',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('72','FO','Faroe Islands',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('73','FJ','Fiji Islands',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('74','FI','Finland',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('75','FR','France',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('76','GF','French Guiana',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('77','PF','French Polynesia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('78','TF','French Southern Territories',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('79','GA','Gabon',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('80','GM','Gambia The',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('81','GE','Georgia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('82','DE','Germany',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('83','GH','Ghana',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('84','GI','Gibraltar',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('85','GR','Greece',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('86','GL','Greenland',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('87','GD','Grenada',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('88','GP','Guadeloupe',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('89','GU','Guam',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('90','GT','Guatemala',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('91','XU','Guernsey and Alderney',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('92','GN','Guinea',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('93','GW','Guinea-Bissau',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('94','GY','Guyana',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('95','HT','Haiti',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('96','HM','Heard and McDonald Islands',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('97','HN','Honduras',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('98','HK','Hong Kong S.A.R.',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('99','HU','Hungary',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('100','IS','Iceland',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('101','IN','India',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('102','ID','Indonesia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('103','IR','Iran',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('104','IQ','Iraq',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('105','IE','Ireland',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('106','IL','Israel',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('107','IT','Italy',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('108','JM','Jamaica',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('109','JP','Japan',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('110','XJ','Jersey',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('111','JO','Jordan',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('112','KZ','Kazakhstan',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('113','KE','Kenya',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('114','KI','Kiribati',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('115','KP','Korea North',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('116','KR','Korea South',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('117','KW','Kuwait',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('118','KG','Kyrgyzstan',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('119','LA','Laos',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('120','LV','Latvia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('121','LB','Lebanon',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('122','LS','Lesotho',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('123','LR','Liberia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('124','LY','Libya',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('125','LI','Liechtenstein',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('126','LT','Lithuania',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('127','LU','Luxembourg',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('128','MO','Macau S.A.R.',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('129','MK','Macedonia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('130','MG','Madagascar',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('131','MW','Malawi',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('132','MY','Malaysia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('133','MV','Maldives',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('134','ML','Mali',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('135','MT','Malta',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('136','XM','Man (Isle of)',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('137','MH','Marshall Islands',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('138','MQ','Martinique',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('139','MR','Mauritania',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('140','MU','Mauritius',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('141','YT','Mayotte',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('142','MX','Mexico',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('143','FM','Micronesia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('144','MD','Moldova',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('145','MC','Monaco',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('146','MN','Mongolia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('147','MS','Montserrat',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('148','MA','Morocco',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('149','MZ','Mozambique',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('150','MM','Myanmar',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('151','NA','Namibia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('152','NR','Nauru',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('153','NP','Nepal',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('154','AN','Netherlands Antilles',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('155','NL','Netherlands The',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('156','NC','New Caledonia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('157','NZ','New Zealand',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('158','NI','Nicaragua',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('159','NE','Niger',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('160','NG','Nigeria',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('161','NU','Niue',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('162','NF','Norfolk Island',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('163','MP','Northern Mariana Islands',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('164','NO','Norway',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('165','OM','Oman',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('166','PK','Pakistan',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('167','PW','Palau',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('168','PS','Palestinian Territory Occupied',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('169','PA','Panama',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('170','PG','Papua new Guinea',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('171','PY','Paraguay',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('172','PE','Peru',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('173','PH','Philippines',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('174','PN','Pitcairn Island',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('175','PL','Poland',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('176','PT','Portugal',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('177','PR','Puerto Rico',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('178','QA','Qatar',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('179','RE','Reunion',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('180','RO','Romania',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('181','RU','Russia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('182','RW','Rwanda',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('183','SH','Saint Helena',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('184','KN','Saint Kitts And Nevis',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('185','LC','Saint Lucia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('186','PM','Saint Pierre and Miquelon',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('187','VC','Saint Vincent And The Grenadines',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('188','WS','Samoa',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('189','SM','San Marino',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('190','ST','Sao Tome and Principe',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('191','SA','Saudi Arabia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('192','SN','Senegal',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('193','RS','Serbia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('194','SC','Seychelles',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('195','SL','Sierra Leone',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('196','SG','Singapore',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('197','SK','Slovakia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('198','SI','Slovenia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('199','XG','Smaller Territories of the UK',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('200','SB','Solomon Islands',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('201','SO','Somalia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('202','ZA','South Africa',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('203','GS','South Georgia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('204','SS','South Sudan',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('205','ES','Spain',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('206','LK','Sri Lanka',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('207','SD','Sudan',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('208','SR','Suriname',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('209','SJ','Svalbard And Jan Mayen Islands',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('210','SZ','Swaziland',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('211','SE','Sweden',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('212','CH','Switzerland',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('213','SY','Syria',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('214','TW','Taiwan',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('215','TJ','Tajikistan',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('216','TZ','Tanzania',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('217','TH','Thailand',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('218','TG','Togo',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('219','TK','Tokelau',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('220','TO','Tonga',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('221','TT','Trinidad And Tobago',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('222','TN','Tunisia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('223','TR','Turkey',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('224','TM','Turkmenistan',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('225','TC','Turks And Caicos Islands',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('226','TV','Tuvalu',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('227','UG','Uganda',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('228','UA','Ukraine',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('229','AE','United Arab Emirates',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('230','GB','United Kingdom',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('231','US','United States',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('232','UM','United States Minor Outlying Islands',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('233','UY','Uruguay',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('234','UZ','Uzbekistan',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('235','VU','Vanuatu',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('236','VA','Vatican City State (Holy See)',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('237','VE','Venezuela',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('238','VN','Vietnam',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('239','VG','Virgin Islands (British)',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('240','VI','Virgin Islands (US)',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('241','WF','Wallis And Futuna Islands',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('242','EH','Western Sahara',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('243','YE','Yemen',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('244','YU','Yugoslavia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('245','ZM','Zambia',NULL,NULL);
insert into `countries` (`id`, `sortname`, `name`, `created_at`, `updated_at`) values('246','ZW','Zimbabwe',NULL,NULL);
